source:      ./source
destination: ./_site
plugins:     ./_plugins
layouts:     _layouts
include: []
exclude: []
keep_files: ['.git']
timezone: nil

future:      true
show_drafts: nil
limit_posts: 0
pygments:    true

relative_permalinks: true

permalink:   /:categories/:year/:month/:title.html
paginate_path: 'page:num'
markdown:    rdiscount
markdown_ext: markdown, mkd, mkdn, md
textile_ext: textile

excerpt_separator: "\n\n"

safe:        false
host: 0.0.0.0
port: 4000
baseurl:    /
lsi: true


maruku:
  use_tex:    false
  use_divs:   false
  png_engine: blahtex
  png_dir:    images/latex
  png_url:    /images/latex

rdiscount:
  extensions: []

redcarpet:
  extensions: []

kramdown:
  auto_ids: true,
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  use_coderay: false

  coderay:
    coderay_wrap: div
    coderay_line_numbers: inline
    coderay_line_numbers_start: 1
    coderay_tab_width: 4
    coderay_bold_every: 10
    coderay_css: style

redcloth:
  hard_breaks: true
