theme = "ahmy"
pygmentsCodeFences = true
pygmentsOptions = "linenos=table"
pygmentsUseClasses = true
disqusShortname = "labs-yulrizka"
baseURL = "https://labs.yulrizka.com/"

[markup.goldmark.renderer]
unsafe = true
